version: '3.8'

services:
  api:
    image: python:3.11
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:8000:8000"
    command: >
      bash -c "pip install -r requirements.txt
               && pip install uvicorn
               && uvicorn app:app --host 0.0.0.0 --port 8000 --reload"
